### ISSUE TITLE
Presence Channel hash error

### ISSUE THREAD

**Issue by niku98** [beyondcode/laravel-websockets#192]
I got this error when trying to join a presence channel.

```sh
Connection id 555337873.285811191 sending message {"event":"pusher_internal:subscription_succeeded","channel":"private-Users.2"}
1351: connection id 555337873.285811191 received message: {"event":"pusher:subscribe","data":{"auth":"333511:f499859e22e3764a511e
780d515ec70447d495f74d7c132be5e5d7bfbfe81312","channel_data":"{\"user_id\":1}","channel":"presence-Rooms.1.Chat"}}.
Exception `ErrorException` thrown: `Undefined property: stdClass::$user_info`
1351: exception `ErrorException` thrown: `Undefined property: stdClass::$user_info`.
```

After read source code I found problem but don't know how to fix. Problem is in **BeyondCode\LaravelWebSockets\WebSockets\Channels\PresenceChannel::getHash**, there is no **$user_info** property in **stdClass $channelData**, only **$user_id**

```php
protected function getHash(): array
{
    $hash = [];

    foreach ($this->users as $socketId => $channelData) {
        $hash[$channelData->user_id] = $channelData->user_info;
    }

    return $hash;
}
```

Below is my code to join channel, send, receive whisper

```javascript
// This block code in created() - Vue component
this.echos.chat = this.Echo.join('Rooms.' + this.room.id + '.Chat').joining(e => {
    console.log(e);
}).listenForWhisper('typing', e => {
    console.log(e.name);
});
```

```javascript
// A method in component
whisperTyping(){
    this.echos.chat.whisper('typing', {
        name: this.curUser.name
    });
},
```

**Comment by dustin-affinityps** [comment]
Did you ever find a solution to this? I'm having the same issue, but have been unable to figure it out.

**Comment by rennokki** [comment]
Weird, it seems from the payload that it sends `"channel_data":"{\"user_id\":1}"`, without `user_info`. Let me address this.

**Comment by rennokki** [comment]
@dustin-affinityps @niku98 I assume you guys are trying to get users into a Presence Channel without authenticating them or...?

**Comment by dustin-affinityps** [comment]
@rennokki I'm authenticating, and the getting the channel_data with user_id correctly, but no user_info is present.

**Comment by rennokki** [comment]
I fixed it, can you somehow be able to try the master version? I have managed somehow to test it locally and worked fine, but I assume it's a bit biased on this point, depending from project to project :eyes:

**Comment by dustin-affinityps** [comment]
I applied your fix and that definitely fixes the errors, I'm just still not sure what I'm doing wrong where user_info isn't being populated. This does work though.

**Comment by rennokki** [comment]
Then we're going to chase the problem down further 👀

**Comment by rennokki** [comment]
@dustin-affinityps Can you show me your channel configuration from `channels.php`?

I see from the Laravel docs that you can broadcast user details on join if you authorize them: https://laravel.com/docs/7.x/broadcasting#authorizing-presence-channels

**Comment by dustin-affinityps** [comment]
`
...
Broadcast::channel('pbx-queue', function($user) {
    if ( auth()->check() ) {
        return $user->toArray();
    }
});
`
